--------------------------------------------------------
--  ÆÄÀÏÀÌ »ý¼ºµÊ - È­¿äÀÏ-11¿ù-05-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CODE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAIN"."CODE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 741 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EXERCISE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAIN"."EXERCISE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PARTY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAIN"."PARTY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence POST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAIN"."POST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence WORKOUT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAIN"."WORKOUT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "TRAIN"."MEMBER" 
   (	"USER_ID" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"PASSWD" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARTICIPANT
--------------------------------------------------------

  CREATE TABLE "TRAIN"."PARTICIPANT" 
   (	"PARTY_ID" NUMBER(*,0), 
	"USER_ID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARTY
--------------------------------------------------------

  CREATE TABLE "TRAIN"."PARTY" 
   (	"PARTY_ID" NUMBER(*,0), 
	"USER_ID" VARCHAR2(30 BYTE), 
	"POST_NUMBER" NUMBER(*,0), 
	"WRITE_DATE" DATE, 
	"TITLE" VARCHAR2(100 BYTE), 
	"CONTENTS" VARCHAR2(4000 BYTE), 
	"PARTY_SIZE" NUMBER(*,0), 
	"LOCATION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRAIN
--------------------------------------------------------

  CREATE TABLE "TRAIN"."TRAIN" 
   (	"CODE" NUMBER(*,0), 
	"ORIGINNO" NUMBER(*,0), 
	"GROUPORD" NUMBER(*,0), 
	"GROUPLAYER" NUMBER(*,0), 
	"TITLE" VARCHAR2(100 BYTE), 
	"CONTENTS" VARCHAR2(1000 BYTE), 
	"USER_ID" VARCHAR2(30 BYTE), 
	"FLAG" NUMBER(*,0), 
	"COLLAPSE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table WORKOUT
--------------------------------------------------------

  CREATE TABLE "TRAIN"."WORKOUT" 
   (	"WORKOUT_ID" NUMBER(*,0), 
	"USER_ID" VARCHAR2(30 BYTE), 
	"WRITE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table WORKOUT_DETAIL
--------------------------------------------------------

  CREATE TABLE "TRAIN"."WORKOUT_DETAIL" 
   (	"EXERCISE_ID" NUMBER(*,0), 
	"WORKOUT_ID" NUMBER(*,0), 
	"EXERCISE" VARCHAR2(100 BYTE), 
	"WEIGHT" NUMBER(*,0), 
	"REPS" NUMBER(*,0), 
	"SETS" NUMBER(*,0), 
	"MEMO" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;